apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.secretStore.namespace }}
spec:
  provider:
    aws:
      region: {{ .Values.secretStore.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.aws.accessKeyID.name }}
            key: {{ .Values.secretStore.aws.accessKeyID.key }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.aws.secretAccessKey.name }}
            key: {{ .Values.secretStore.aws.secretAccessKey.key }}
